languange: generic
sudo: required 
services:
 - docker

before_install:
 - docker build -t ejjj/react-test -f ./client/Dockerfile.dev ./client

script:
 - docker run -e CI=true ejjj/react-test npm test

after_sucess:
 - docker build -t ejjj/multi-client ./client
 - docker build -t ejjj/multi-nginx ./nginx
 - docker build -t ejjj/multi-server ./server
 - docker byild -t ejjj/multi-worker ./worker

# Log in to the docker CLI
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# Take those images and push them to docker hub

 - docker push ejjj/multi-client
 - docker push ejjj/multi-nginx
 - docker push ejjj/multi-server
 - docker push ejjj/multi-worker

deploy:
 edge: true
 provider: elasticbeanstalk
 region: us-east-2
 app: multi-docker
 env: MultiDocker-env
 bucket_name: elasticbeanstalk-us-east-2-535466068727
 bucket_path: docker-multi
 on: 
  branch: master
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key: $AWS_SECRET_KEY

